#!name=TikTok LU
#!desc= (IOS >= 15) Unlock TikTok (VPN Region Luxembourg) 
#!openUrl=https://github.com/Semporia/TikTok-Unlock
#!author=Semporia
#!homepage=https://github.com/Semporia/TikTok-Unlock
#!icon= https://raw.githubusercontent.com/Semporia/Hand-Painted-icon/master/Social_Media/TikTok.png

//Сhanged the region to make it work in russia
[URL Rewrite]
(?<=_region=)RU(?=&) LU 307
(?<=&mcc_mnc=)4 2 307
^(https?:\/\/(tnc|dm)[\w-]+\.\w+\.com\/.+)(\?)(.+) $1$3 302
(^https?:\/\/*\.\w{4}okv.com\/.+&.+)(\d{2}\.3\.\d)(.+) $118.0$3 302

[MITM]
hostname = %APPEND% *.tiktokv.com,*.byteoversea.com,*.tik-tokapi.com
